trigger: none
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    # pool: default
    displayName: Build job
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: QA
  displayName: QA stage
  jobs:  
  - job: Test
    displayName: QA job
    steps:
    - script: echo Hello, world! This is testing
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'